name: Ola Mundo
on: push
jobs:
  minha-tarefa:
    runs-on: ubuntu-latest
    steps:
      - name: Dizer ola
        run: echo "Olá Raiane."
      - name: Dizer ola
        run: echo "Commit feito por ${{ github.actor }}"
